### ISSUE TITLE
[H264][Encoder] Encoder will generate invalid frames when encoding to the VAProfileH264ConstrainedBaseline 

### ISSUE THREAD

**Issue by angelo-p** [01org/libyami#738] opened 2017-05-15 20:45 UTC
I edited the yamiencode source code to target the the VAProfileH264ConstrainedBaseline:
Index: tests/encode.cpp
===================================================================
--- tests/encode.cpp	(revision 830693)
+++ tests/encode.cpp	(working copy)
@@ -77,6 +77,7 @@
     VideoParamsCommon encVideoParams;
     encVideoParams.size = sizeof(VideoParamsCommon);
     encoder->getParameters(VideoParamsTypeCommon, &encVideoParams);
+    encVideoParams.profile = VAProfileH264ConstrainedBaseline;
     setEncoderParameters(&encVideoParams);
     encVideoParams.size = sizeof(VideoParamsCommon);
     encoder->setParameters(VideoParamsTypeCommon, &encVideoParams);

- libva test app produces a correct h264 file:
h264encode  --profile BP --fourcc NV12 -w 1280  -h 720  --srcyuv /tmp/stromae_368x208_100frames.nv12  -o /tmp/stromae_baseline_profile.h264 

- yamiencode  produce an invalid (garbled video)   h264 file:
yamiencode -i /tmp/stromae_368x208_100frames.nv12 -s NV12 -W368 -H208 -o /tmp/stromae_baseline_profile.h264

Can you please take a look ?
Thanks,
  Angelo

**Comment by xuguangxin** [comment] 2017-05-16 06:07
Hi @wudping , 
please help this

**Comment by wudping** [comment] 2017-05-16 06:43
hi @angelo-p ,
I set the profile as your code, It can work well on my end.
index 58760bf..242d55a 100644
--- a/tests/encode.cpp
+++ b/tests/encode.cpp
@@ -80,6 +80,7 @@ int main(int argc, char** argv)
     VideoParamsCommon encVideoParams;
     encVideoParams.size = sizeof(VideoParamsCommon);
     encoder->getParameters(VideoParamsTypeCommon, &encVideoParams);
+    encVideoParams.profile = VAProfileH264ConstrainedBaseline;
     setEncoderParameters(&encVideoParams);
     encVideoParams.size = sizeof(VideoParamsCommon);
     encoder->setParameters(VideoParamsTypeCommon, &encVideoParams);

My command line:
yamiencode -s NV12 -i out_176x144_10frame.yuv -W 176 -H 144 -o dd_nv12.264

**Comment by wudping** [comment] 2017-05-16 06:45
Hi @xuguangxin ,
The pull request [86](https://github.com/01org/libyami-utils/pull/86) implements the profile setting, please help to merge it, thanks.

**Comment by angelo-p** [comment] 2017-05-17 02:21
Hi Guys,
Thanks for looking into this.
That's odd,   I'll try with others input files, could it be video size related?

**Comment by xuguangxin** [comment] 2017-05-19 07:33
Maybe, @wudping could you share you resolution here. thanks

**Comment by wudping** [comment] 2017-05-22 07:57
Hi @angelo-p , @xuguangxin,
**Commands:**
[dpwu@supperkbl:265_debug]$**yamiencode -i h264_enc_yuv/1024x768_500F_001.I420 -N 50 -o dd_1024x768.264**
libva info: VA-API version 0.40.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /home/dpwu/source_code/src_yami_apc/bin_yami_verify/vaapi/lib/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_40
libva info: va_openDriver() returns 0
**wdp  vaapiencoder_h264.cpp ensureSequenceHeader 1614, m_videoParamCommon.profile = 13, VAProfileH264ConstrainedBaseline = 13 ====
wdp  vaapiencoder_h264.cpp ensureSequenceHeader 1614, m_videoParamCommon.profile = 13, VAProfileH264ConstrainedBaseline = 13 ====**
encode done

**Resolutions tested is okay to encode with the above command:**
1024x768
1280x720
176x144
1920x1080
192x128
352x288
368x208

**Comment by angelo-p** [comment] 2017-05-22 15:45
Hi Dongping,


- my OS version is Ubuntu 16.04.2 LTS 64bits :

lsb_release -a
No LSB modules are available.
Distributor ID:    Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:    16.04
Codename:    xenial


- my test file has a video resolution of 368x208     stride=384 .

yamiencode -i /tmp/stromae_368x208_100frames.nv12   -s NV12 -W368 -H208 -o /tmp/stromae.h264


- I generated the test file using ffmpeg:

ffmpeg -i /tmp/stromae.mp4 -vframes 100 -vcodec rawvideo -pix_fmt nv12  /tmp/stromae_368x208_100frames.nv12


- I use ffplay to verify the produced encoded file:

ffplay   /tmp/stromae.h264


- yamiinfo output:

yamiinfo
libyamiutils 1.0.1 - https://github.com/01org/libyami-utils
API: 0.3.2
decoders:
    image/jpeg
    video/avc
    video/h264
    video/h265
    video/x-vnd.on2.vp8
encoders:
    video/avc
    video/h264
post processors:
    vpp/scaler



Also, I don't know if this is relevant, but I am using  the  1.0.1-RC1  version of the libs:

angelo@angelo-nuc:~/git/libyami$ git status
HEAD detached at libyami-1.0.1-RC1


angelo@angelo-nuc:~/git/libyami-utils$ git status
HEAD detached at 1.0.1-RC1

- I added my input and output test files to my dropbox account :
https://www.dropbox.com/sh/9h6dkpm9tlrnrau/AABusFsUkOy2uZ6KVmhf77tca?dl=0 


Thanks,
  Angelo




________________________________

**Comment by wudping** [comment] 2017-05-24 02:43
hi @angelo-p ,
I have reproduced the issue on Libyami tag libyami-1.0.1-RC1, libyami-utils tag 1.0.1-RC1.

I use tag 1.2.0-RC2 to implement the profile setting, it's okay. Maybe you can have a try on it.
**Libyami:** 
**tag:** 1.2.0-RC2
**commit ID:** c884fc3facbf1a0adf2082a1cf95cb146300a5ca

**libyami-utils:**
**tag:** 1.2.0-RC2
**commit ID:** b480c0594a7e761a8ccfe6b19b3f9bd0c3d871a1

**cmd:**
yamiencode -i sss_1920x1080.nv12 -s NV12  -o dd_1920x1080_1.264

**Comment by angelo-p** [comment] 2017-05-26 21:33
Hi  wudping,
I am happy to confirm that using  tag 1.2.0-RC2,  the encoding to VAProfileH264ConstrainedBaseline is correct.

Thanks a lot to all of you for your support,
Angelo

**Comment by wudping** [comment] 2017-05-27 00:49
You are welcome, @angelo-p .

**Comment by xuguangxin** [comment] 2017-06-26 04:22
close this since it fixed.

Hi @angelo-p , 
please ping use if you have any problem
thanks

**Closed as completed by xuguangxin** 2017-06-26 04:22 UTC
