### ISSUE TITLE
265 encoding with a few wrong color

### ISSUE THREAD

**Issue by wudping** [01org/libyami#455] opened 2016-03-11 01:28 UTC
1.Testing environment:
 libyami: (master)684272026f5533300efc02e77ec125b945965c22
 2.Test command
yamiencode -i ss_1280x720.I420 -W 1280 -H 720 -o dd1.265 -c EVC  -s NV12
yamidecode -i dd1.265 
3. Test result
1) in the last frame, an error is: Nal Data is incomplete while parsing coeff_abs_level_remaining syntax variable of Slice Data
2) In some frames, there are a few  wrong color bars between two different color blocks.

**Comment by lizhong1008** [comment] 2016-03-11 06:28
Hi,Dongping: I can't reproduce test result 1, can you try it agian? I've reproduce result 2.

**Comment by wudping** [comment] 2016-03-11 09:34
sorry, I can't reproduce it again, even encoding the same I420 file.

**Comment by xuguangxin** [comment] 2016-07-06 03:26
close this since you can't reproduce it

**Closed by xuguangxin** 2016-07-06 03:26 UTC
