### ISSUE TITLE
[H264][Encoder] Encoder will generate invalid frame when the gop size is larger than 2000

### ISSUE THREAD

**Issue by jsorg71** [01org/libyami#670] opened 2016-11-27 04:54 UTC
If you set m_videoParamCommon.intraPeriod to -1, you get bad frames after 2048 frames.
This error is printed.
libyami error 18172 (bitWriter.cpp, 74): Write Bits Error: value overflow
If you let it run, after about 2000 more frames, it works again and you get another good 2048 frames and this repeats.
If you set m_videoParamCommon.intraPeriod to something like 1024 it's ok.

**Comment by lizhong1008** [comment] 2016-11-28 05:23
intraPeriod is unsigned int, why set it to be -1?

**Comment by jsorg71** [comment] 2016-11-28 05:32
When you set unsigned int to -1 it sets max int.
This is setting unlimited GOP.

**Comment by lizhong1008** [comment] 2016-11-28 05:40
we defined the maximum IDR period in vaapiencode_h264.cpp.  Unlimited GOP is not supported right now.
#define MAX_IDR_PERIOD 2000

**Comment by jsorg71** [comment] 2016-11-28 05:49
Yea, the check needs to be fixed.  It used to work.

**Comment by lizhong1008** [comment] 2016-11-28 06:21
@jsorg71 It is not a good idea to set unlimited GOP, it will cause bad encode quality and bad fault tolerant.

**Comment by jsorg71** [comment] 2016-11-28 06:35
Lets leave unlimited GOP aside, the check should be fixed.

**Comment by lizhong1008** [comment] 2016-11-28 06:50
@jsorg71 so are you going to close this issue?

**Comment by jsorg71** [comment] 2016-11-28 08:14
@lizhong1008 I'll close it if you don't care that users can set this and get invalid frames when this was not true with older libyami.

**Comment by jsorg71** [comment] 2016-11-28 08:43
Don't think about unlimited GOP.
The same thing happens if you set m_videoParamCommon.intraPeriod to 2048.

**Comment by xuguangxin** [comment] 2016-11-29 02:17
@lizhong1008 , I think @jsorg71 is right, -1 for uint only means a really large value. If set -1 have problem in 2000 frames.  set 3000 frames should have similar problem too. We should avoid generate invalid frame no matter user set any value. right?

**Comment by lizhong1008** [comment] 2016-11-29 02:51
@jsorg71 we are not going to support unlimited GOP right now unless users have strong reason. But yes, we need to check the invalid frame issue.  Sorry I was not to push you close it just because I misunderstood you.  I will check the invalid  frames issue.

**Comment by xuguangxin** [comment] 2016-11-30 06:46
Hi @jsorg71 ,
If you set gop size to a large value. any error bit will have side effect to later pictures. Could you share your use scenario ? Why you want unlimited GOP size?

**Comment by jsorg71** [comment] 2016-12-01 05:33
@xuguangxin for remote desktop and video conferencing, no B frames and infinite GOP length is preferred.  There is no issues with error bit.
The perfered GOP is
I P P P P P P ...... forever.

**Comment by jsorg71** [comment] 2016-12-01 18:56
@xuguangxin 
Here is the way I configure yami

```
    self->handle = g_createEncoder(YAMI_MIME_H264);
    if (self->handle == 0)
    {
        g_free(enc);
        g_free(self);
        return 0;
    }
    g_memset(&nd, 0, sizeof(nd));
    nd.type = NATIVE_DISPLAY_DRM;
    g_encodeSetNativeDisplay(self->handle, &nd);

    g_memset(&encVideoParams, 0, sizeof(encVideoParams));
    encVideoParams.size = sizeof(VideoParamsCommon);
    status = g_getParameters(self->handle, VideoParamsTypeCommon, &encVideoParams);
    if (status != ENCODE_SUCCESS)
    {
        g_releaseEncoder(self->handle);
        g_free(enc);
        g_free(self);
        return 0;
    }
    encVideoParams.resolution.width = width;
    encVideoParams.resolution.height = height;
    encVideoParams.size = sizeof(VideoParamsCommon);

    encVideoParams.rcMode = RATE_CONTROL_CQP;
    encVideoParams.rcParams.initQP = 28;
    encVideoParams.intraPeriod = -1;

    status = g_setParameters(self->handle, VideoParamsTypeCommon, &encVideoParams);
    if (status != ENCODE_SUCCESS)
    {
        g_releaseEncoder(self->handle);
        g_free(enc);
        g_free(self);
        return 0;
    }

    g_memset(&streamFormat, 0, sizeof(streamFormat));
    streamFormat.size = sizeof(VideoConfigAVCStreamFormat);
    status = g_getParameters(self->handle, VideoConfigTypeAVCStreamFormat, &streamFormat);
    if (status != ENCODE_SUCCESS)
    {
        g_releaseEncoder(self->handle);
        g_free(enc);
        g_free(self);
        return 0;
    }
    streamFormat.streamFormat = AVC_STREAM_FORMAT_ANNEXB;
    status = g_setParameters(self->handle, VideoConfigTypeAVCStreamFormat, &streamFormat);
    if (status != ENCODE_SUCCESS)
    {
        g_releaseEncoder(self->handle);
        g_free(enc);
        g_free(self);
        return 0;
    }

    status = g_encodeStart(self->handle);
    if (status != ENCODE_SUCCESS)
    {
        g_releaseEncoder(self->handle);
        g_free(enc);
        g_free(self);
        return 0;
    }
```
for comparison, here is how I configure nvenv
```
    session->initParams.version = NV_ENC_INITIALIZE_PARAMS_VER;
    session->initParams.encodeGUID = NV_ENC_CODEC_H264_GUID;
    session->initParams.presetGUID = NV_ENC_PRESET_LOW_LATENCY_DEFAULT_GUID;
    session->initParams.encodeWidth = width;
    session->initParams.encodeHeight = height;
    session->initParams.darWidth = width;
    session->initParams.darHeight = height;
    session->initParams.frameRateNum = 30;
    session->initParams.frameRateDen = 1;
    session->initParams.enableEncodeAsync = 0; /* Sync Mode */
    session->initParams.enablePTD = 1;
    session->initParams.reportSliceOffsets = 0;
    session->initParams.enableSubFrameWrite = 0;
    session->initParams.encodeConfig = &(session->config);
    session->initParams.maxEncodeWidth = MAX_ENC_WIDTH;
    session->initParams.maxEncodeHeight = MAX_ENC_HEIGHT;

    session->config.profileGUID = NV_ENC_H264_PROFILE_MAIN_GUID;
    session->config.gopLength = NVENC_INFINITE_GOPLENGTH;
    session->config.frameIntervalP = 1;  /* 1 + B_Frame_Count */
    session->config.frameFieldMode = NV_ENC_PARAMS_FRAME_FIELD_MODE_FRAME;
    session->config.mvPrecision = NV_ENC_MV_PRECISION_QUARTER_PEL;
    session->config.rcParams.rateControlMode = NV_ENC_PARAMS_RC_CONSTQP;
    session->config.rcParams.averageBitRate = 5000000;
    session->config.rcParams.maxBitRate = 0;
    session->config.rcParams.vbvBufferSize = 0;
    session->config.rcParams.vbvInitialDelay = 0;
    session->config.rcParams.constQP.qpInterP = 28;
    session->config.rcParams.constQP.qpInterB = 28;
    session->config.rcParams.constQP.qpIntra = 28;
    session->config.encodeCodecConfig.h264Config.chromaFormatIDC = 1;
    session->config.encodeCodecConfig.h264Config.idrPeriod =
                                            NVENC_INFINITE_GOPLENGTH;
```

**Comment by xuguangxin** [comment] 2016-12-02 05:57
Hi @jsorg71 
Sorry to introduce inconvenience to you. We will change code to support this. But it may need some time to test it. As temporary workaround you can comment out two lines at
https://github.com/01org/libyami/blob/apache/encoder/vaapiencoder_h264.cpp#L1043

thanks

**Comment by jsorg71** [comment] 2016-12-02 06:52
Thanks, don't worry about inconvenience.
I only want to help the project and I hope remote desktop will be a supported scenario.
I can change thous 2 lines but I think the invalid frame issue will need to be fixed first.

**Comment by xuguangxin** [comment] 2016-12-02 06:57
Hi @jsorg71 
Yes, really thanks for your help. We are opensource project. Community user like you is very important to us.  The 2000 failed frame you mentioned is caused by `#define MAX_IDR_PERIOD 2000`, so remove two lines will not have the 2000 problem.

thanks.

**Comment by lizhong1008** [comment] 2016-12-06 07:52
@jsorg71,  please help to verify https://github.com/01org/libyami/pull/676.  It should fix the invalid frame issue.  Unlimited GOP is not supported right now because it need much time to verify. If you think it is strongly necessary, please create a separate github issue. Thanks.

**Comment by xuguangxin** [comment] 2016-12-12 23:49
@jsorg71 is any update on this. Is it fix your problem?
thanks

**Comment by jsorg71** [comment] 2016-12-13 00:28
@lizhong1008 You head of apache branch like 01org head of apache branch does not work for other reason.  For some reason, all set / set parameters fails cause the struct sizes does match.
If I checkout fa3865a3406f9f21b729d5b6d46536a7e70eb391 I don't have the problem.
So until that's fixes, I can't test.  I have no idea what changed to cause this and I don't have time this week to look.

**Comment by xuguangxin** [comment] 2016-12-13 00:50
Hi @jsorg71 , you may need remove previously installed headers, since the API change.

**Comment by jsorg71** [comment] 2016-12-13 01:00
@xuguangxin Thanks for tip.  I can't find were it's getting the wrong headers.  I have a script that cleans and builds, if I just change to checkout fa3865a3406f9f21b729d5b6d46536a7e70eb391 it works.  I install with a prefix and I delete the directory first.  Strange.

**Comment by xuguangxin** [comment] 2016-12-13 01:04
I have this issue before, usually because you have other copy of headers in other directory; "find /usr -name Yami.h" may help on this.

**Comment by lizhong1008** [comment] 2016-12-13 01:39
@jsorg71 maybe you can try two steps: 1. remove previous libyami and libyami-util installation 2. build latest libyami and libyam-util.  If you still have such issue, please let us know.

**Comment by jsorg71** [comment] 2016-12-13 19:27
I think it's because a bool was added to the struct.
It's 1 byte in c++ and 4 in c.

**Comment by jsorg71** [comment] 2016-12-13 22:46
Yes, this seems to fix it for me
```
diff --git a/interface/VideoCommonDefs.h b/interface/VideoCommonDefs.h
index 48ab207..4bf854d 100644
--- a/interface/VideoCommonDefs.h
+++ b/interface/VideoCommonDefs.h
@@ -49,7 +49,7 @@ extern "C" {

 #ifndef __cplusplus
 #ifndef bool
-#define bool  int
+#define bool  char
 #endif

 #ifndef true
```

**Comment by jsorg71** [comment] 2016-12-14 00:18
Anyway with that change it works and I see there is a PR that may fix this #680 
But when I set intraPeriod to -1 I see this error after a while.
libyami error 2109 (bitWriter.cpp, 74): Write Bits Error: value overflow
libyami error 2108 (bitWriter.cpp, 74): Write Bits Error: value overflow
libyami error 2107 (bitWriter.cpp, 74): Write Bits Error: value overflow
libyami error 2110 (bitWriter.cpp, 74): Write Bits Error: value overflow
libyami error 2109 (bitWriter.cpp, 74): Write Bits Error: value overflow
libyami error 2108 (bitWriter.cpp, 74): Write Bits Error: value overflow
libyami error 2107 (bitWriter.cpp, 74): Write Bits Error: value overflow
libyami error 2110 (bitWriter.cpp, 74): Write Bits Error: value overflow
...
Actually, anything over 1024 causes this error.  Should we just cap the user's setting at 1024?

**Comment by lizhong1008** [comment] 2016-12-14 01:22
@jsorg71 , daf7703a6c061f35c5da4e797fccbc20985b47ca should fix the "value overflow" issue, and I've tested it. Are you using latest libyami apache branch?

**Comment by jsorg71** [comment] 2016-12-14 21:41
@lizhong1008 with all that was going on, yes, I was on wrong branch.  Now that the bool fix has been merged in apache branch, it works.
Thanks.

**Comment by xuguangxin** [comment] 2016-12-15 06:05
Hi @jsorg71 , thanks for your feedback, I will close this. If you still have problem please help to create another issue

**Closed as completed by xuguangxin** 2016-12-15 06:05 UTC
Labels: bug, fix before 16Q4
