### ISSUE TITLE
[Decode][H265] The MD5 values are not the same as the reference date when doing H265 decode test by using JVT clips

### ISSUE THREAD

**Issue by keqiaox** [01org/libyami#297] opened 2015-09-01 06:10 UTC
1.Testing environment:
Libva: (master)c74f846b8e9c94a4b52b2e32f12d8c9fe62a93af
Libva_intel_driver: (master)ae75deb4fcb9743803c07adef9b23776c399aae3
libyami: (master)183e322d3bd96bb57d451cebca3bcc2b499ba4bc
ffmpeg: (master) 859731d64271f4b30b1ceb9412092023d5991b1d
2.Test command:
1.$ ./yamidecode -i /media/HEVC/JVT10.0/$filename -m -2 -f I420
2.Failed cases:
  1---PICSIZE_A_Bossen_1.bin
  2---PICSIZE_B_Bossen_1.bin 
  3---PICSIZE_C_Bossen_1.bin 
  4---PICSIZE_D_Bossen_1.bin 

libyami do not support large resolutions of these four videos currently.

**Comment by xuguangxin** [comment] 2015-09-08 04:20
need update status after we rebased code.

**Comment by xuguangxin** [comment] 2015-09-21 01:38
hi @andyLiuChina , please update this.

**Comment by andyLiuChina** [comment] 2015-09-21 02:13
OK,  I had updated!

**Comment by xuguangxin** [comment] 2015-12-29 08:31
hi @andyLiuChina , do we have this 4 clips in regression test set? If yes maybe we can close it

**Comment by xuguangxin** [comment] 2016-06-12 07:19
this should close since we do not support so large picture size in driver.

**Comment by xuguangxin** [comment] 2016-07-06 03:34
close this since driver do not support this size

**Closed by xuguangxin** 2016-07-06 03:34 UTC
