### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by jeason2014** [01org/libyami#371] opened 2015-12-07 09:50 UTC
compiler:gcc version 5.2.1 20151003 (Ubuntu 5.2.1-21ubuntu2) )
==================================================
In file included from /usr/include/c++/5/algorithm:62:0,
                 from vaapidecoder_h265.cpp:38:
/usr/include/c++/5/bits/stl_algo.h: In instantiation of '_ForwardIterator std::__remove_if(_ForwardIterator, _ForwardIterator, _Predicate) [with _ForwardIterator = std::_Rb_tree_const_iterator<std::tr1::shared_ptr<YamiMediaCodec::VaapiDecPictureH265> >; _Predicate = __gnu_cxx::__ops::_Iter_pred<bool (*)(const std::tr1::shared_ptr<YamiMediaCodec::VaapiDecPictureH265>&)>]':
/usr/include/c++/5/bits/stl_algo.h:936:30:   required from '_FIter std::remove_if(_FIter, _FIter, _Predicate) [with _FIter = std::_Rb_tree_const_iterator<std::tr1::shared_ptr<YamiMediaCodec::VaapiDecPictureH265> >; _Predicate = bool (*)(const std::tr1::shared_ptr<YamiMediaCodec::VaapiDecPictureH265>&)]'
vaapidecoder_h265.cpp:280:76:   required from here
/usr/include/c++/5/bits/stl_algo.h:868:23: error: no match for 'operator=' (operand types are 'const std::tr1::shared_ptr<YamiMediaCodec::VaapiDecPictureH265>' and 'const std::tr1::shared_ptr<YamiMediaCodec::VaapiDecPictureH265>')
             *__result = _GLIBCXX_MOVE(*__first);
                       ^
In file included from /usr/include/c++/5/tr1/memory:50:0,
                 from ../interface/VideoCommonDefs.h:29,
                 from ../interface/VideoDecoderDefs.h:28,
                 from ../interface/VideoDecoderInterface.h:27,
                 from vaapidecoder_base.h:27,
                 from vaapidecoder_factory.h:24,
                 from vaapidecoder_h265.cpp:31:
/usr/include/c++/5/tr1/shared_ptr.h:1031:9: note: candidate: std::tr1::shared_ptr<_Tp>& std::tr1::shared_ptr<_Tp>::operator=(const std::tr1::shared_ptr<_Tp1>&) [with _Tp1 = YamiMediaCodec::VaapiDecPictureH265; _Tp = YamiMediaCodec::VaapiDecPictureH265] <near match>
         operator=(const shared_ptr<_Tp1>& __r) // never throws
         ^
/usr/include/c++/5/tr1/shared_ptr.h:1031:9: note:   passing 'const std::tr1::shared_ptr<YamiMediaCodec::VaapiDecPictureH265>*' as 'this' argument discards qualifiers
/usr/include/c++/5/tr1/shared_ptr.h:1040:9: note: candidate: template<class _Tp1> std::tr1::shared_ptr<_Tp>& std::tr1::shared_ptr<_Tp>::operator=(std::auto_ptr<_Tp1>&) [with _Tp1 = _Tp1; _Tp = YamiMediaCodec::VaapiDecPictureH265]
         operator=(std::auto_ptr<_Tp1>& __r)
         ^
/usr/include/c++/5/tr1/shared_ptr.h:1040:9: note:   template argument deduction/substitution failed:
In file included from /usr/include/c++/5/algorithm:62:0,
                 from vaapidecoder_h265.cpp:38:
/usr/include/c++/5/bits/stl_algo.h:868:23: note:   types 'std::auto_ptr<_Tp1>' and 'const std::tr1::shared_ptr<YamiMediaCodec::VaapiDecPictureH265>' have incompatible cv-qualifiers
             *__result = _GLIBCXX_MOVE(*__first);
                       ^
In file included from /usr/include/c++/5/tr1/memory:50:0,
                 from ../interface/VideoCommonDefs.h:29,
                 from ../interface/VideoDecoderDefs.h:28,
                 from ../interface/VideoDecoderInterface.h:27,
                 from vaapidecoder_base.h:27,
                 from vaapidecoder_factory.h:24,
                 from vaapidecoder_h265.cpp:31:
/usr/include/c++/5/tr1/shared_ptr.h:985:11: note: candidate: std::tr1::shared_ptr<YamiMediaCodec::VaapiDecPictureH265>& std::tr1::shared_ptr<YamiMediaCodec::VaapiDecPictureH265>::operator=(const std::tr1::shared_ptr<YamiMediaCodec::VaapiDecPictureH265>&) <near match>
     class shared_ptr
           ^
/usr/include/c++/5/tr1/shared_ptr.h:985:11: note:   passing 'const std::tr1::shared_ptr<YamiMediaCodec::VaapiDecPictureH265>*' as 'this' argument discards qualifiers
Makefile:596: recipe for target 'libyami_decoder_la-vaapidecoder_h265.lo' failed
make[2]: *** [libyami_decoder_la-vaapidecoder_h265.lo] Error 1

**Comment by uartie** [comment] 2015-12-07 16:59
This is a duplicate of #334... and has already been fixed.

**Comment by xuguangxin** [comment] 2015-12-08 03:53
Hi jeason2014
you can try latest version in master

**Comment by xuguangxin** [comment] 2015-12-11 04:28
close this since it fixed by #334 .

Hi @jeason2014 
you can reopen this if it still have this issue.

**Closed by xuguangxin** 2015-12-11 04:28 UTC
