### ISSUE TITLE
[yamiVPP][regression] Green block appear when doing scaling test

### ISSUE THREAD

**Issue by keqiaox** [01org/libyami#432] opened 2016-01-28 07:52 UTC
1.Testing environment:
libva: (master) cb418f6ef36b6e6f0d632bf7c0aaf035a271400b
intel_driver: (master) 2110b3a0bca6cecb42defd0b01d32530f5807b04
cmrt: (master) fb93006e483c32601b374d4ced71d5f911d2d416
intel_hybrid_driver: (master) 0375a7287e556fedaf7628a85b143c1233a9ef84
ffmpeg: (master) 1d8f9b7d1ad2a58f612b47e769d00e6f8891d881
libyami: (master) 7df2e93d98ab3d0b9fe2bf1725eb491edcb6d37d

2.Test command:
$ ./yamivpp ./yv12/1920x1080.yv12 ./output/case4_704x576.i420

3.Failed cases:
1.scaling to 704x576 resolution。
2.with error message when doing the test: libyami error 10504 (vaapipostprocess_scaler.cpp, 62): invalid fourcc, set color stand to bt601

**Comment by xuguangxin** [comment] 2016-07-25 06:56
Hi @wang-fei & @keqiaox 
Can't reproduce this issue, Could you double check this or provide some platform information to me using internal mail?

**Comment by ghost** [comment] 2016-07-26 01:25
checked with:
7f2e0329121ddd6b4a48df97d871fc2b47bfde47 apache branch
no this issue. So close it.

**Closed by ghost** 2016-07-26 01:25 UTC
Labels: fix before 16Q3
